# Generated by Django 5.2.1 on 2025-05-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
