version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.example

  web:
    build: .
    container_name: django-app
    command: sh -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
        - /app/.venv
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.example

volumes:
  postgres_data:
